from manim import *
import numpy as np

class Sustituye(Scene):
    def construct(self):
        ec_ini = MathTex("y = 2 \cdot", "x", " + 1").scale(3).shift(3*UP)
        ec_2 = MathTex("y = 2 \cdot", "(\ \ \ )", " + 1").scale(3).shift(1.5*UP)
        ec_3 = MathTex("y = 2 \cdot", "(\ \ \ )", " + 1").scale(3).shift(1.5*UP)
        x_1 = MathTex("-1").scale(3).shift(LEFT + 3*DOWN)
        x_1_in = MathTex("-1").scale(3).move_to(ec_2[1])
        x_2_in = MathTex("1").scale(3).move_to(ec_2[1])
        x_2 = MathTex("1").scale(3).shift(2*RIGHT + 3*DOWN)
        y_1 = MathTex("1").scale(3).next_to(ec_2[0], RIGHT)
        y_2 = MathTex("3").scale(3).next_to(ec_2[0], RIGHT)
        for ter in ec_ini:
            self.play(Create(ter))
        self.play(FadeIn(ec_2))
        self.wait(1)
        self.play(FadeIn(x_1))
        self.wait(1)
        eje_x = NumberLine().shift(2.5*DOWN).add_numbers()
        punto_x_1 = Dot(np.array([-1,0,0])).scale(2).shift(2.5*DOWN)
        punto_x_2 = Dot(np.array([1,0,0])).scale(2).shift(2.5*DOWN)

        self.add(eje_x, punto_x_1)
        self.wait(2)
        self.play(Transform(x_1, x_1_in))
        self.wait(1)
        self.play(Transform(ec_2, y_1), Uncreate(x_1))
        self.wait(1)
        self.play(Uncreate(ec_2))
        self.wait(1)
        self.play(punto_x_1.animate.shift(DOWN))
        self.wait(1)
        self.play(FadeIn(ec_2))
        self.play(FadeIn(x_2))
        self.wait(1)
        self.add(eje_x, punto_x_2)
        self.wait(2)
        self.play(Transform(x_2, x_2_in))
        self.wait(1)
        self.play(Transform(ec_2, y_2), Uncreate(x_2))
        self.wait(1)
        self.play(Uncreate(ec_2))
        self.wait(1)
        self.play(punto_x_2.animate.shift(3*UP))
        recta = Line(3*LEFT + 5*DOWN, 3*RIGHT + 7*UP).set_color(YELLOW).shift(2.5*DOWN)
        self.wait(1)
        self.play(Create(recta))
        self.wait(2)